### ISSUE TITLE
Using LMS course copy breaks assignments: steps to reproduce

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support-legacy#146]
**Describe the bug**
When instructors copy a course in Canvas students can run into an authorization loop. This is possibly intermittent, but we've been able to reproduce it consistently in assignments using Canvas Files.

**To Reproduce**
See comment below.

**Expected behavior**
In Canvas: Instructors expect to copy a course, have students authorize once, and have them access the assignment.
In other LMSs: Instructors expect to copy a course and for assignments to "just work" in the new course.

**Comment by mkdir-washington-edu** [comment]
Steps to reproduce the behavior:
1. Log-ins for Canvas instructors and students are here: https://docs.google.com/document/d/1Nl-ytl92Ydg-Z-1oQjUQUW_tt_AIVxXctrYXMD1Eqzs/edit
2. Create an Assignment in a Canvas Course using a PDF Canvas Files - https://web.hypothes.is/help/using-the-hypothesis-app-with-assignments-in-canvas/
3. In the course's left hand menu, click "Settings"
4. In the right hand menu click "Copy this Course"
5. Click "Create Course"
6. In the new course, in the left hand menu, click Settings
7. Publish the Course
8. In the new course, in the left hand menu, click "People"
9. Click "+People" and add a student to the new Course
10. Log in as that student
11. Enter the new course and go to "Assignments"
12. Click on the Canvas Files assignment
13. Attempt to authorize Hypothesis. Experience the loop.

**Comment by robertknight** [comment]
I wonder if this is happening because we are identifying Canvas files using an ID and that ID changes from the original to the copied assignment.

**Comment by klemay** [comment]
Steps to reproduce in Blackboard:

[teacher and student logins available in Blackboard]

1. Create a course with at least 1 Hypothesis-enabled reading
2. Follow [these instructions](https://help.blackboard.com/Learn/Instructor/Course_Content/Reuse_Content/Copy_Courses) to copy the contents of that course to a new course (
3. Access the course site as a teacher - you'll note that the links to the Hypothesis-enabled readings are broken

**Comment by klemay** [comment]
Steps to reproduce in Moodle:

[teacher and student logins available in 1Password]

1. Create or enter a course with at least 1 Hypothesis-enabled reading
2. In the left navigation menu, go to Site Administration > Courses > Manage courses and categories
3. Find the course you wish to copy under the "Miscellaneous" heading
4. Next to the course title, click on the Duplicate icon (next to the cog; looks like 2 sheets of paper)
5. Name your new course and click "copy and view"
6. Once the copying process is complete, go to your new course
7. Click on any Hypothesis-enabled reading in the new course. You'll see that the original content link isn't preserved - when you click on the link as a teacher, you'll be prompted to re-link a document or web page to the assignment

To quickly see what this looks like in a copied course, see: https://hypothesisuniversity.moodlecloud.com/course/view.php?id=17

**Comment by robertknight** [comment]
Related Slack thread about LTI specification support for course copying: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1604478759046900
