### ISSUE TITLE
Feature request - add comments to grades via the grading bar

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support-legacy#159]
**Request**
Some users have asked for the ability to add comments to a grade when using the LMS app. This is in addition to leaving replies to student annotations; comments can apply to an overall assignment, give rationale for a grade, and are viewed privately by the student so critique can be given that is not visible to the rest of the class.

This is already a feature in Canvas SpeedGrader:
![image](https://user-images.githubusercontent.com/22603275/98837251-bf26cd80-2410-11eb-9542-c53e055d8a51.png)

... but is not currently available through our Grading Bar in other LMSs.

Blackboard: While instructors can annotate a submitted document and leave feedback, I'm not sure there's a way to leave an overall comment in Blackboard Assignments. https://help.blackboard.com/Learn/Student/Assignments/Assignment_Grades

Moodle: This looks possible for instructors in Moodle assignments:m https://it.umn.edu/services-technologies/how-tos/moodle-32-provide-feedback-comments#quick_grading.

Sakai: This looks possible in Sakai: http://blog.teachingandlearning.unc.edu/2013/10/30/provide-students-with-feedback-in-sakai/

**Additional context**
Support only has one logged ticket with this feature request, but Support and Sales have been hearing folks ask for it in webinars.

**Comment by marcospri** [comment]
Done
