### ISSUE TITLE
Grading bar being out of 10 points gives confusing gradebook entries for some instructors

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support-legacy#187]
**Describe the bug**
The Hypothesis grading bar has instructors grade assignments out of 10 points, and then sends that grade as a proportion to the LMS due to the LTI integration. This sets up potentially confusing Gradebook results for instructors. For example, an instructor had an assignment worth 3 points and so gave her lowest-scoring students 3/10 in Hypothesis, and then had to re-grade all of the .9s in the Gradebook so they would become 1s.

It is also not immediately apparent to users that they can use decimals in this field. Nor will all users jump right to using decimals.

We also see confusion for some users when they first encounter this. They assume Hypothesis will pull in the max grade of the assignment, and for assignments whose max grade is not 10 they assume we're either pointing to wrong assignment or we've changed the max grade on them.

**To Reproduce**
1. Create a non-Canvas assignment with a max grade of three points.
2. Access the assignment as a student.
3. As a teacher, grade that student, endeavoring to give them a 1/3. 
4. See the results in the gradebook.

**Expected behavior**
The expected result would be to make it as easy as possible for instructors to:
- Understand Hypothesis isn't showing their max grade (assuming showing the actual max grade is impossible).
- Grade their Hypothesis assignments, getting the correct result in their Gradebook.

**Additional context**
An example of an this issue: https://app.hubspot.com/contacts/6291320/ticket/336148794/

**Comment by mattdricker** [comment]
Another example of user confusion https://app.hubspot.com/contacts/6291320/ticket/374590754/

**Comment by mkdir-washington-edu** [comment]
Also found here: https://github.com/hypothesis/product-backlog/issues/1279

**Comment by marcospri** [comment]
Done a little bit better since https://github.com/hypothesis/lms/issues/5505
